/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.73.0
  Forc version: 0.49.2
  Fuel-Core version: 0.22.0
*/

import { Interface, Contract, ContractFactory } from "fuels";
import type { Provider, Account, AbstractAddress, BytesLike, DeployContractOptions, StorageSlot } from "fuels";
import type { MultisigContractAbi, MultisigContractAbiInterface } from "../MultisigContractAbi";

const _abi = {
  "types": [
    {
      "typeId": 0,
      "type": "()",
      "components": [],
      "typeParameters": null
    },
    {
      "typeId": 1,
      "type": "[_; 2]",
      "components": [
        {
          "name": "__array_element",
          "type": 2,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 2,
      "type": "b256",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 3,
      "type": "bool",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 4,
      "type": "enum ExecutionError",
      "components": [
        {
          "name": "CanOnlyCallContracts",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "IncorrectSignerOrdering",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "InsufficientAssetAmount",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "InsufficientApprovals",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "TransferRequiresAValue",
          "type": 0,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 5,
      "type": "enum Identity",
      "components": [
        {
          "name": "Address",
          "type": 16,
          "typeArguments": null
        },
        {
          "name": "ContractId",
          "type": 21,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 6,
      "type": "enum InitError",
      "components": [
        {
          "name": "CannotReinitialize",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "NotInitialized",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "ThresholdCannotBeZero",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "TotalWeightCannotBeLessThanThreshold",
          "type": 0,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 7,
      "type": "enum MessageFormat",
      "components": [
        {
          "name": "None",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "EIP191PersonalSign",
          "type": 0,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 8,
      "type": "enum MessagePrefix",
      "components": [
        {
          "name": "None",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "Ethereum",
          "type": 0,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 9,
      "type": "enum Option",
      "components": [
        {
          "name": "None",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "Some",
          "type": 13,
          "typeArguments": null
        }
      ],
      "typeParameters": [
        13
      ]
    },
    {
      "typeId": 10,
      "type": "enum TransactionParameters",
      "components": [
        {
          "name": "Call",
          "type": 20,
          "typeArguments": null
        },
        {
          "name": "Transfer",
          "type": 31,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 11,
      "type": "enum TypeToHash",
      "components": [
        {
          "name": "Threshold",
          "type": 29,
          "typeArguments": null
        },
        {
          "name": "Transaction",
          "type": 30,
          "typeArguments": null
        },
        {
          "name": "Weight",
          "type": 34,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 12,
      "type": "enum WalletType",
      "components": [
        {
          "name": "Fuel",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "EVM",
          "type": 0,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 13,
      "type": "generic T",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 14,
      "type": "raw untyped ptr",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 15,
      "type": "str",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 16,
      "type": "struct Address",
      "components": [
        {
          "name": "value",
          "type": 2,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 17,
      "type": "struct AssetId",
      "components": [
        {
          "name": "value",
          "type": 2,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 18,
      "type": "struct B512",
      "components": [
        {
          "name": "bytes",
          "type": 1,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 19,
      "type": "struct Bytes",
      "components": [
        {
          "name": "buf",
          "type": 24,
          "typeArguments": null
        },
        {
          "name": "len",
          "type": 35,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 20,
      "type": "struct ContractCallParams",
      "components": [
        {
          "name": "calldata",
          "type": 19,
          "typeArguments": null
        },
        {
          "name": "forwarded_gas",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "function_selector",
          "type": 19,
          "typeArguments": null
        },
        {
          "name": "single_value_type_arg",
          "type": 3,
          "typeArguments": null
        },
        {
          "name": "transfer_params",
          "type": 31,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 21,
      "type": "struct ContractId",
      "components": [
        {
          "name": "value",
          "type": 2,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 22,
      "type": "struct EvmAddress",
      "components": [
        {
          "name": "value",
          "type": 2,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 23,
      "type": "struct ExecuteTransactionEvent",
      "components": [
        {
          "name": "nonce",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "target",
          "type": 5,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 24,
      "type": "struct RawBytes",
      "components": [
        {
          "name": "ptr",
          "type": 14,
          "typeArguments": null
        },
        {
          "name": "cap",
          "type": 35,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 25,
      "type": "struct RawVec",
      "components": [
        {
          "name": "ptr",
          "type": 14,
          "typeArguments": null
        },
        {
          "name": "cap",
          "type": 35,
          "typeArguments": null
        }
      ],
      "typeParameters": [
        13
      ]
    },
    {
      "typeId": 26,
      "type": "struct SetThresholdEvent",
      "components": [
        {
          "name": "previous_threshold",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "threshold",
          "type": 35,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 27,
      "type": "struct SetWeightEvent",
      "components": [
        {
          "name": "user",
          "type": 32,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 28,
      "type": "struct SignatureInfo",
      "components": [
        {
          "name": "message_format",
          "type": 7,
          "typeArguments": null
        },
        {
          "name": "message_prefix",
          "type": 8,
          "typeArguments": null
        },
        {
          "name": "signature",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "wallet_type",
          "type": 12,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 29,
      "type": "struct Threshold",
      "components": [
        {
          "name": "contract_identifier",
          "type": 21,
          "typeArguments": null
        },
        {
          "name": "nonce",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "threshold",
          "type": 35,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 30,
      "type": "struct Transaction",
      "components": [
        {
          "name": "contract_identifier",
          "type": 21,
          "typeArguments": null
        },
        {
          "name": "nonce",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "target",
          "type": 5,
          "typeArguments": null
        },
        {
          "name": "transaction_parameters",
          "type": 10,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 31,
      "type": "struct TransferParams",
      "components": [
        {
          "name": "asset_id",
          "type": 17,
          "typeArguments": null
        },
        {
          "name": "value",
          "type": 9,
          "typeArguments": [
            {
              "name": "",
              "type": 35,
              "typeArguments": null
            }
          ]
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 32,
      "type": "struct User",
      "components": [
        {
          "name": "address",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "weight",
          "type": 35,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 33,
      "type": "struct Vec",
      "components": [
        {
          "name": "buf",
          "type": 25,
          "typeArguments": [
            {
              "name": "",
              "type": 13,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "len",
          "type": 35,
          "typeArguments": null
        }
      ],
      "typeParameters": [
        13
      ]
    },
    {
      "typeId": 34,
      "type": "struct Weight",
      "components": [
        {
          "name": "contract_identifier",
          "type": 21,
          "typeArguments": null
        },
        {
          "name": "nonce",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "user",
          "type": 32,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 35,
      "type": "u64",
      "components": null,
      "typeParameters": null
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "users",
          "type": 33,
          "typeArguments": [
            {
              "name": "",
              "type": 32,
              "typeArguments": null
            }
          ]
        }
      ],
      "name": "constructor",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "signatures",
          "type": 33,
          "typeArguments": [
            {
              "name": "",
              "type": 28,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "target",
          "type": 5,
          "typeArguments": null
        },
        {
          "name": "transaction_parameters",
          "type": 10,
          "typeArguments": null
        }
      ],
      "name": "execute_transaction",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "signatures",
          "type": 33,
          "typeArguments": [
            {
              "name": "",
              "type": 28,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "threshold",
          "type": 35,
          "typeArguments": null
        }
      ],
      "name": "set_threshold",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "signatures",
          "type": 33,
          "typeArguments": [
            {
              "name": "",
              "type": 28,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "user",
          "type": 32,
          "typeArguments": null
        }
      ],
      "name": "set_weight",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "user",
          "type": 2,
          "typeArguments": null
        }
      ],
      "name": "approval_weight",
      "output": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset_id",
          "type": 17,
          "typeArguments": null
        }
      ],
      "name": "balance",
      "output": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "attributes": null
    },
    {
      "inputs": [
        {
          "name": "type_to_hash",
          "type": 11,
          "typeArguments": null
        }
      ],
      "name": "compute_hash",
      "output": {
        "name": "",
        "type": 2,
        "typeArguments": null
      },
      "attributes": null
    },
    {
      "inputs": [],
      "name": "nonce",
      "output": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "threshold",
      "output": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    }
  ],
  "loggedTypes": [
    {
      "logId": 0,
      "loggedType": {
        "name": "",
        "type": 6,
        "typeArguments": []
      }
    },
    {
      "logId": 1,
      "loggedType": {
        "name": "",
        "type": 6,
        "typeArguments": []
      }
    },
    {
      "logId": 2,
      "loggedType": {
        "name": "",
        "type": 6,
        "typeArguments": []
      }
    },
    {
      "logId": 3,
      "loggedType": {
        "name": "",
        "type": 6,
        "typeArguments": []
      }
    },
    {
      "logId": 4,
      "loggedType": {
        "name": "",
        "type": 4,
        "typeArguments": []
      }
    },
    {
      "logId": 5,
      "loggedType": {
        "name": "",
        "type": 4,
        "typeArguments": []
      }
    },
    {
      "logId": 6,
      "loggedType": {
        "name": "",
        "type": 16,
        "typeArguments": []
      }
    },
    {
      "logId": 7,
      "loggedType": {
        "name": "",
        "type": 22,
        "typeArguments": []
      }
    },
    {
      "logId": 8,
      "loggedType": {
        "name": "",
        "type": 4,
        "typeArguments": []
      }
    },
    {
      "logId": 9,
      "loggedType": {
        "name": "",
        "type": 4,
        "typeArguments": []
      }
    },
    {
      "logId": 10,
      "loggedType": {
        "name": "",
        "type": 15,
        "typeArguments": null
      }
    },
    {
      "logId": 11,
      "loggedType": {
        "name": "",
        "type": 4,
        "typeArguments": []
      }
    },
    {
      "logId": 12,
      "loggedType": {
        "name": "",
        "type": 4,
        "typeArguments": []
      }
    },
    {
      "logId": 13,
      "loggedType": {
        "name": "",
        "type": 16,
        "typeArguments": []
      }
    },
    {
      "logId": 14,
      "loggedType": {
        "name": "",
        "type": 22,
        "typeArguments": []
      }
    },
    {
      "logId": 15,
      "loggedType": {
        "name": "",
        "type": 4,
        "typeArguments": []
      }
    },
    {
      "logId": 16,
      "loggedType": {
        "name": "",
        "type": 4,
        "typeArguments": []
      }
    },
    {
      "logId": 17,
      "loggedType": {
        "name": "",
        "type": 23,
        "typeArguments": []
      }
    },
    {
      "logId": 18,
      "loggedType": {
        "name": "",
        "type": 6,
        "typeArguments": []
      }
    },
    {
      "logId": 19,
      "loggedType": {
        "name": "",
        "type": 6,
        "typeArguments": []
      }
    },
    {
      "logId": 20,
      "loggedType": {
        "name": "",
        "type": 6,
        "typeArguments": []
      }
    },
    {
      "logId": 21,
      "loggedType": {
        "name": "",
        "type": 16,
        "typeArguments": []
      }
    },
    {
      "logId": 22,
      "loggedType": {
        "name": "",
        "type": 22,
        "typeArguments": []
      }
    },
    {
      "logId": 23,
      "loggedType": {
        "name": "",
        "type": 4,
        "typeArguments": []
      }
    },
    {
      "logId": 24,
      "loggedType": {
        "name": "",
        "type": 4,
        "typeArguments": []
      }
    },
    {
      "logId": 25,
      "loggedType": {
        "name": "",
        "type": 26,
        "typeArguments": []
      }
    },
    {
      "logId": 26,
      "loggedType": {
        "name": "",
        "type": 6,
        "typeArguments": []
      }
    },
    {
      "logId": 27,
      "loggedType": {
        "name": "",
        "type": 16,
        "typeArguments": []
      }
    },
    {
      "logId": 28,
      "loggedType": {
        "name": "",
        "type": 22,
        "typeArguments": []
      }
    },
    {
      "logId": 29,
      "loggedType": {
        "name": "",
        "type": 4,
        "typeArguments": []
      }
    },
    {
      "logId": 30,
      "loggedType": {
        "name": "",
        "type": 4,
        "typeArguments": []
      }
    },
    {
      "logId": 31,
      "loggedType": {
        "name": "",
        "type": 6,
        "typeArguments": []
      }
    },
    {
      "logId": 32,
      "loggedType": {
        "name": "",
        "type": 27,
        "typeArguments": []
      }
    }
  ],
  "messagesTypes": [],
  "configurables": [
    {
      "name": "THRESHOLD",
      "configurableType": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "offset": 39012
    }
  ]
};

const _storageSlots: StorageSlot[] = [
  {
    "key": "b48b753af346966d0d169c0b2e3234611f65d5cfdb57c7b6e7cd6ca93707bee0",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "de9090cb50e71c2588c773487d1da7066d0c719849a7e58dc8b6397a25c567c0",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "f383b0ce51358be57daa3b725fe44acdb2d880604e367199080b4379c41bb6ed",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  }
];

export class MultisigContractAbi__factory {
  static readonly abi = _abi;

  static readonly storageSlots = _storageSlots;

  static createInterface(): MultisigContractAbiInterface {
    return new Interface(_abi) as unknown as MultisigContractAbiInterface
  }

  static connect(
    id: string | AbstractAddress,
    accountOrProvider: Account | Provider
  ): MultisigContractAbi {
    return new Contract(id, _abi, accountOrProvider) as unknown as MultisigContractAbi
  }

  static async deployContract(
    bytecode: BytesLike,
    wallet: Account,
    options: DeployContractOptions = {}
  ): Promise<MultisigContractAbi> {
    const factory = new ContractFactory(bytecode, _abi, wallet);

    const { storageSlots } = MultisigContractAbi__factory;

    const contract = await factory.deployContract({
      storageSlots,
      ...options,
    });

    return contract as unknown as MultisigContractAbi;
  }
}
